### ISSUE TITLE
Kirin as a playable race? 

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#111]
I think they could be a very fun race as long as they aren't given nearly as wide an array of spells as unicorns so they don't end up being "cooler unicorns" mechanic-wise (perhaps simply restricted to the spells they're seen doing in the show? which would be telekinesis, if I'm remembering right) and have them rely more on their race specific skills, like fire/heat immunity and their nirik transformation, which could allow them to trail fire (that can spread slightly more effectively than normal minecraft fire and cause increased destruction like in the show if possible) and perhaps allow them certain fire related attacks in this form at the cost of magic, while holding the nirik form itself could cost hunger like pegasus flight, or vice versa, whichever you feel works best :)

**Comment by BlasterM5** [comment]
Have it where the Kirin as to build "rage" to activate Nirik form - like have it where the Kirin builds rage from taking damage, and when rage hits the max, or when the user activates it - fire.

**Comment by MimzyFang** [comment]
those are my ideas for that species:
   - Kirin can change into a Nirik at 10 health and changes into one automatically at 6 health
can use magic in both forms but anything not related to fire is likely going to fail in Nirik
   - If a Nirik casts a fire related spell it's much stronger
   - Nirik can't distinguish friend or foe every entity looks like a hostile mob to them
   - Kirin are bad at swimming due to their fur getting heavy 
   - Nirik get damaged by standing in water but not rain as it evaporates before touching the creature
   - Can eat both meat and plant products
   - fire resistant in Nirik
   - everything that touches a Nirik or everything that gets damaged by a Nirik gets set on fire

**Comment by PrinceDrowsy** [comment]
>     * Nirik get damaged by standing in water but not rain as it evaporates before touching the creature

heh, a steam effect would be fun

**Comment by BlasterM5** [comment]
A bit overbalanced. The only type of creature that should be damaged by water is an elemental creature that is directly hurt by contacting water, or an enderman. It doesn't make sense for Kirin to be damaged by water, not even as a gameplay mechanic. Buuuuut, it could be that landing in water prevents using Nirik mode or fire abilities, or perhaps, defuses the ability.

**Comment by MimzyFang** [comment]
> A bit overbalanced. The only type of creature that should be damaged by water is an elemental creature that is directly hurt by contacting water, or an enderman. It doesn't make sense for Kirin to be damaged by water, not even as a gameplay mechanic. Buuuuut, it could be that landing in water prevents using Nirik mode or fire abilities, or perhaps, defuses the ability.

it was more meant as throw things at the wall and see what sticks approach to brainstorming, and I basically put in everything that came to my mind and I like your suggestion ^^
