### ISSUE TITLE
Flight in beta is buggy

### ISSUE THREAD

**Issue by Swifter46ter** [Sollace/Unicopia#117]
In the reworked flight patch, flight is much more difficult and unforgiving.  A few issues are as follows.

While flying forward, even while holding space, you will sometimes lose altitude control and sometimes dive straight down to the ground.  This is not due to water or biomes, I have tested that it happens in superflat as well.  It is purely a random chance glitch that can kill you and ruins flight.  Flying over cold or ocean biomes is also impossible now, since maintaining altitude is even harder with this glitchy flight.

You cannot hover anymore, no matter how much you abuse the left shift button..  After about thirty seconds, you just fall.

Being able to dive and lower altitude on command is very useful and a great addition, but I'd rather go back to the previous flight system if I can't control when it happens.  

Update: I noticed that there's an altitude limit of 320.  Why? That's equally as annoying.

Another possibility could be a gamerule to disable the sinking while gliding.  I don't like the mechanic at all.
Either that, or.. instead of sink rate I'd add elytra style diving.  Even just wearing an elytra and switching between regular flying and diving with an elytra in previous updates was more enjoyable than the current method of shedding altitude fast.

**Comment by Sollace** [comment]
> While flying forward, even while holding space

Holding space won't stop you from falling. It will make it slower, but you're really supposed to use shift to flap your wings to reset the descent rate now.

There is a small bug in the released beta that will cause you to bump upwards when switching into the hovering state, however that's been fixed on my end.

> Update: I noticed that there's an altitude limit of 320. Why? That's equally as annoying.

I haven't tested it in higher altitudes. Hitting shift should help you get higher though.

Levelling up to increase your stamina (and mana levels) will also help with flying for longer as well.

**Comment by Sollace** [comment]
Altitude doesn't have a limit. You can go as far as you have stamina. Once your mana bar is empty, you can keep going at the cost of hunger and health, but generally it's expected you find somewhere to rest before you reach this point.

Note: Levelling up will give you a larger mana cap and let you fly for longer. This is how far I got at max level.

![image](https://github.com/Sollace/Unicopia/assets/6429283/d7cb7077-1e59-4880-8a1f-4db70ae9d4e4)

For flapping, every flap gives you a slight upwards momentum but the majority of the boost goes in the direction you're looking. You also have to space them out otherwise they won't have their full power.

The hovering issue is a **bug**. I went and looked at that, and I believe part of it was fixed in this commit https://github.com/Sollace/Unicopia/commit/75a0c4d769f851f2f0eeef218c39b1d58cdd6ab0

**Comment by Swifter46ter** [comment]
Ahh, I see now.  Thanks for looking into the bug report, I love how active and open the development has been.  My friend has been reporting a few bugs I found in the past and I thought I'd share the hovering bug I came across.  You're doing Celestia's work with this amazing mod!
