### ISSUE TITLE
Failure to Launch

### ISSUE THREAD

**Issue by Homsar3** [Sollace/Unicopia#180]
Game fails to launch with following log (1.2.0 beta 6)
[log.txt](https://github.com/Sollace/Unicopia/files/12542881/log.txt)

**Comment by MimzyFang** [comment]
Don't think that will fix your issue but please update your prismlauncher

**Comment by Sollace** [comment]
Please update Fabric API

**Comment by Homsar3** [comment]
> 

After checking mondrinth and curseforge I swear I'm up-to-date with Fabric API (0.83.0+1.20)

**Comment by Sollace** [comment]
Hm. Then perhaps you could try switching to 1.20.1. It's possible I broke compatibility with 1.20.0 with this release since it depends on a newer fabric-api.

Should be at least version 0.85.0+1.20.1

Edit: Looks like fabric is not supporting 1.20 for newer builds. Only 1.19.4, 1.20.1, and 1.20.2. Any mods that worked on 1.20 should still work on 1.20.1 so I see no reason you should have to stay on that version.
