### ISSUE TITLE
black holes need a size cap

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#326]
![2024-04-07_01 06 37](https://github.com/Sollace/Unicopia/assets/43648117/72ebcabc-181d-4e9c-927f-adcf06a9a7b2)
![2024-04-07_01 06 34](https://github.com/Sollace/Unicopia/assets/43648117/f26f710d-6038-4bed-a1c1-ab5d2b0c9216)
![2024-04-07_01 06 07](https://github.com/Sollace/Unicopia/assets/43648117/b577361b-0569-42c3-b0f7-c228f3d52b6b)
![2024-04-07_01 06 03](https://github.com/Sollace/Unicopia/assets/43648117/9f68bac4-c838-40b3-b4c1-16c9b0436320)

**Comment by LotusCookie** [comment]
![image](https://github.com/Sollace/Unicopia/assets/119984509/b445e1b9-45cc-42b4-9cb6-081b7ab2ee8f)

Seems to mostly be a problem if you put the spell underground, but.. Yeah, if it gets to the size where it can break blocks, it will quickly grow to world-destroying size.

It seems that bedrock and barriers are actually safe from the black hole, but some things like gravestones can get destroyed.

**Comment by MimzyFang** [comment]
For the last thing lotus mentioned a config with an array and the possibility to decide what blocks it can break would be quiet useful for modpack makers and maybe even make it possible to configure the max size so that if someone wanted they could restore the current behavior by setting that to like -1 or something

**Comment by Sollace** [comment]
This is done/fixed. I went and rewrote the logic for the black holes somewhat to no longer share code with the shield which fixes a whole swath of issues.

To summarise:
1. It will now break blocks in chunks rather than all at once
2. The diameter is capped to between 1 and 25 blocks (configurable by the `maxDarkVortexSize` gamerule)
3. Blocks in the `unicopia:catapult_immune` are excluded from being affected by black holes now too (add your tombstones to that)
4. The black hole now creates an explosion when it can no longer sustain itself from it's creator's mana (previously would silently dissapear)
5. Black holes now explode when they collide with each other (paradoxially, it's now safer to have two black holes than one)
6. Black hole's growth rate has been made logarithmic with the function `diameter = (1 - (1/(1 + mass))) * maxRadius`
7. Changed various particle and rendering effects to make it look better

**Comment by MimzyFang** [comment]
Is it possible to uncap the black hole diameter limit while this would not be useful in survival it could be funny if a creative test world also is the diameter measured in meters I assume it is and if so could you increase the max to 100
Also what is the default

**Comment by Sollace** [comment]
> Is it possible to uncap the black hole diameter limit while this would not be useful in survival it could be funny if a creative test world also is the diameter measured in meters I assume it is and if so could you increase the max to 100 Also what is the default

The default is 20, and chose 25 as the max-max because the game becomes unplayable above that.
