### ISSUE TITLE
[Suggestion] Balancing the Seapony Amulet

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#340]
The seapony amulet's ease of accessibility makes the game a little *too* easy when it comes to accessing the game's underwater loot early. I was thinking making the crafting recipe a little more difficult with the addition of the heart of the sea or another rarer item could fix that. I also feel that it'd make the item a bit more accurate to the show in difficulty of accessibility.

**Comment by Sollace** [comment]
The pearl necklace is meant to be easily accessible for hippogriffs who want to play as seaponies from early game.

**Comment by MimzyFang** [comment]
> The pearl necklace is meant to be easily accessible for hippogriffs who want to play as seaponies from early game.

An alternative way would be to just add a seapony button to the hippogriff species selector and make sure they spawn in the closest ocean to spawn then from there if they wanted to go to land they would need to find everything to craft the necklace making it a cool early game challenge

**Comment by MimzyFang** [comment]
The code to add more tribes to a species could also be reused to add a reformed changeling button to the changeling down the line

**Comment by PrinceDrowsy** [comment]
> The code to add more tribes to a species could also be reused to add a reformed changeling button to the changeling down the line

I think these are pretty good alternatives, hippogriffs could also have an option to automatically spawn with the necklace to avoid having to deal with the more difficult crafting recipe maybe? Could have options to alter this in config as needed perhaps?

**Comment by Sollace** [comment]
1. I dislike mods that give you stuff when you spawn/respawn
2. I dislike the idea of giving certain tribes an immersion-breaking "gib me thing nao plox" button. It has to be tied to some in-universe progression or mechanic, or obtainable naturally through gameplay.

The necklace is made to be something you have to obtain but also not prohibitively unreasonable to get access to in the early game, both for the players that want to play as seaponies from the start, or who play as one on occassion but still shouldn't have to get stuck somewhere unable to find one because they died as a seapony.

I'll think of other way to maybe balance it a little more, but making it borderline impossible to find or giving certain races its powers from the get-go does not to me sound like the right way to do it.

**Comment by PrinceDrowsy** [comment]
> 1. I dislike mods that give you stuff when you spawn/respawn
> 
>     2. I dislike the idea of giving certain tribes an immersion-breaking "gib me thing nao plox" button. It has to be tied to some in-universe progression or mechanic, or obtainable naturally through gameplay.
> 
> 
> The necklace is made to be something you have to obtain but also not prohibitively unreasonable to get access to in the early game, both for the players that want to play as seaponies from the start, or who play as one on occassion but still shouldn't have to get stuck somewhere unable to find one because they died as a seapony.
> 
> I'll think of other way to maybe balance it a little more, but making it borderline impossible to find or giving certain races its powers from the get-go does not to me sound like the right way to do it.

Completely fair! I look forward to whatever decision you make.
