### ISSUE TITLE
The Pegasus Is OP, So Here's A Wall Of Text With My Ideas

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#356]
Pegasi Are Kinda Ridiculously OP. I Would Know, Playing As One All The Time. The End Fight Becomes A Literal Joke, The Void Means Absolutely Nothing, Mobs Cannot Threaten You In Any Way Whatsoever, And You Can Even Fly Indefinitely If You Click V To Stop And Start Flying Periodically Mid-Air. Is It Fun? Yeah, Admittedly. Does It Throw Balancing Out The Window? Also Yes.

I Have A Few Ideas On How To Nerf The Pegasus So You Can't Just Make Everything "Lightwork No Reaction: The Game."

1. Have No Flying In The End Until The Dragon Is Defeated. Maybe The Dragon Has Some Kind Of Spell Preventing Flight, Maybe The Crystals Are The Cause. Regardless Of However You Wish To Spin It, The Fact You Can Cheese The Crystals Or Straight Up Leave To The Outer Islands For Free Is Silly, And Just Temporarily Removing Flight Whenever The Dragon Is Alive Would Fix That.

2. Add Flying Mobs That Pose A Threat To Pegasi. Maybe Pegasi Zomponies Can Fly, And More Frequently On Higher Difficulties. Maybe There's Entirely New Monsters That Live In The Clouds And Only Attack Anypony That Dares To Enter The Sky, Think Crawltipede From Terraria. For The Nether, Perhaps A Mosquito Thing Like How BetterNether Seems To Do It, Idk I Don't Have Ideas For The Nether. For The End, A Simple Fix Would Be To Change How Phantoms Spawn, Making Them Spawn In The Outer Islands Like Regular Monsters, Would Also Make Repairing The Elytra Easier. You Could Also Give Endermares The Ability To Fly, But Honestly Something With 40hp, That Can Teleport, AND Can Fly Would Probably Be A Tad Overkill.

3. Give Skeletons Better Aim And Priority On Flying Pegasi. Just Making It More Difficult To Fly Around When There's A Skeleton Isn't A Bad Idea On It's Own. It's Simple, It's Effective, Occam's Razor For The Win. Though This Doesn't Really Help If The Pegasus Flies Well Above The Skeleton, But That's Why I Suggested Flying Mobs.

4. Make Pegasi Lose Mana When Damaged While Flying, And Potentially Knocked Out Of The Sky If On Low Mana Already. Combos Great With Previous Points About Skeletons And Flying Mobs. The Fact You Can Kinda Just Tank An Arrow To The Face Mid-Flight And Not Have Any Real Turbulence Feels Wrong, But I Can Also See Flying Mobs Being Able To Do That At Random Being Kinda Annoying. So Maybe Tie It To Difficulty And Level, Or Even A Gamerule.
_mana? stamina? pegasi don't use magic, but whatever, i'll keep calling it mana for simplicity._

5. Have No Flight In Enclosed Spaces. Being Able To Fly In A Cave Makes Them A Whole Lot Less Dangerous, Even Though Caves Are Meant To Be That. There's Tons Of Mobs Spawning From The Lack Of Light, The Deeper You Go The More Spawn. But In Big Areas Underground, You Can Just Nuh Uh That And Escape Scot Free. So My Idea Is To Just Remove The Ability To Fly If The Area Is Too Enclosed. Simple In Concept, Though I Can Imagine It Might Be Harder To Code Than Just Flying Enemies.

6. Add Spells To Counter Flight. Only Really Useful In A PVP Setting, But Who Said That Was A Bad Thing? Maybe Some Kind Of Spell Like How Pokémon's Gravity Move Works. Maybe Something Along The Lines Of A Homing Projectile, Think Magic Missile. Maybe Even Just A Beam Spell That Acts Like Hitscan, That Would Make Targeting Flying Pegasi A Lot Easier Seeing How You Don't Need To Adjust For A Projectile's Arc And Speed. Ideally, These Spells Would Have Other Uses Outside Of Just Countering Pegasi And Their Ability To Fly, But They Should Have That Usage Still.

7. Add A Block That Creates A Flight Deadzone. Focusing On PVP Again, A Block That Generates A No-Fly Zone In Exchange For Something Like Valuables Sounds Invaluable For Somepony Who Doesn't Want To Account For Going Over Their Defences Entirely. Mini-Idea: Do The Same With A Magic Deadzone Generator, Since Spells Can Be Just As Ridiculous, And Pegasi Could Even Use Those To Counter Anti-Flight Spells On Their Land.

8. Have No Flying In The Nether. Seriously, The Lava Oceans Just Become A Non-Issue As A Pegasus, And Bastions Can Be Cheesed So Easily By Flying Above Piglin Brutes And Dumping Lava On Them From Out Of Reach- Or Better Yet, Tricking Them To Fall Into Lava. So An Easy Fix Is To Just Disallow Flight In The Nether Entirely. Maybe You Need Some Kind Of Special Item To Allow You To Fly In The Nether, Kinda Like A Wings Of Icarus Type Accessory. Would Bring Back The Challenge That The Nether Is Meant To Have.

9. Have No Infinite Flight With Clicking V Occasionally. Ok This Is 100% A Bug/Exploit, But Here's How It Works: While Flying, And Low Enough On Stamina To Take Damage, Click V To Stop Flying, And Click V Again Quickly To Start Flying Again. For A Bit Of Time, You Won't Take Any Damage. Then Just Repeat Whenever The Screen Flashes Red. Regardless Of Any Other Suggestion I've Made, This Is Easily The Most Important Addition Since It's Pretty Clearly An Unintended Feature That Makes The Usage Of Mana Whilst Flying Useless.

⠀

Wow, This Is Easily My Longest Issue Yet. But I Had A Lot Of Ideas I Wanted To Pitch, And Also That V-Flight Bug As I'll Call It. Hope Some Of These Get Considered, Especially The Idea Of Phantoms Regularly Spawning In The End Since You Already Get The Elytra In The End, And Phantoms Drop Membranes Which Are Used To Repair The Elytra, And It'd Make Phantoms More Interesting Rather Than That One Thing That Appears Sometimes At Night, And- _honestly, my issues with how mojang designed the phantom are for another day._
Have A Good Day, To Anyone Who Actually Read All Of This.

**Comment by PrinceDrowsy** [comment]
I have mixed feelings on the End suggestion. Rather than eliminating flight entirely, I think it'd be better to add an obstacle instead. Perhaps forcefields around the crystals that need to be broken? The dragon breathing fire at you midair? Or perhaps having phantoms spawn in the End to chase after those in flight. I think that'd give a fun additional use to them, which they definitely deserve to receive. They're very fun to fight when in flight, especially with a polearm. Just difficult enough to be rewarding, but not too difficult to be punishing.

The sirens from Equestria Girls/later episodes of MLP are actually seen to be capable of flight, which would be my suggestion for a flying mob! However, I do also quite like the pegasus zombie suggestion as well. In regards to mobs, I definitely hold a preference for things from the canon show or already existing in Minecraft but expanded on for MLP.

I'm a big fan of the better skeleton aim pitch, and the ability to knock pegasi out of the skies with a well-timed arrow or magical blast.

In regards to no flight in enclosed spaces, I'm less keen toward. I think it's unnecessary, and makes things a little less fun. However, you could have the wind system be altered for caves to automatically flow toward the exit to increase difficulty (as well as accuracy to real life), as you would be flying against the wind to fly further into the cave system. 

For "deadzone" blocks, I think a redstone block that generates a strong wind current in whatever direction the block is aimed in could be more fun instead, and have more practical uses on top of that.

No flying in the nether has the same issue of just not being very fun. Heat rises, so having additionally strong wind currents in the Nether should give some mild nerfing while still providing the fun of attempting to fly through the current nonetheless, and should you get stronger with higher levels, you can eventually work towards gaining the ability to better fight these winds and stay afloat more easily, allowing a goal to aim for.

In general, I do think all the points made are valid points to be brought up, I just think the first solution for nerfing should always be adding obstacles rather than eliminating uses of the feature entirely.

**Comment by EternaDash** [comment]
> I have mixed feelings on the End suggestion. Rather than eliminating flight entirely, I think it'd be better to add an obstacle instead. Perhaps forcefields around the crystals that need to be broken? Or perhaps having phantoms spawn in the End to chase after those in flight. I think that'd give a fun additional use to them, which they definitely deserve to receive. They're very fun to fight when in flight, especially with a polearm. Just difficult enough to be rewarding, but not too difficult to be punishing.
> 
> The sirens from Equestria Girls/later episodes of MLP are actually seen to be capable of flight, which would be my suggestion for a flying mob! However, I do also quite like the pegasus zombie suggestion as well. In regards to mobs, I definitely hold a preference for things from the canon show or already existing in Minecraft but expanded on for MLP.
> 
> I'm a big fan of the better skeleton aim pitch, and the ability to knock pegasi out of the skies with a well-timed arrow or magical blast.
> 
> In regards to no flight in enclosed spaces, I'm less keen toward. I think it's unnecessary, and makes things a little less fun. However, you could have the wind system be altered for caves to automatically flow toward the exit to increase difficulty, as you would be flying against the wind to fly further into the cave system.
> 
> For "deadzone" blocks, I think a redstone block that generates a strong wind current in whatever direction the block is aimed in could be more fun instead, and have more practical uses on top of that.
> 
> No flying in the nether has the same issue of just not being very fun. Heat rises, so having additionally strong wind currents in the Nether should give some mild nerfing while still providing the fun of attempting to fly through the current nonetheless, and should you get stronger with higher levels, you can eventually work towards gaining the ability to better fight these winds and stay afloat more easily, allowing a goal to aim for.
> 
> In general, I do think all the points made are valid points to be brought up, I just think the first solution for nerfing should always be adding obstacles rather than eliminating uses of the feature entirely.

Honestly That's A Fair Way Of Thinking.
For The Nether, Even With Harder Flight, If You Can Fly At All You Can Skip Most Of The Challenge Of Getting To A Fortress, And I Find It Often Leaves Non-Pegasi Behind In The Dust From Multiplayer Sessions With My Friends, And That Is Something I'd Like To Avoid.

With The End, Thinking About It, I Suppose Another Way Of Looking At It Would Be To Make The Crystals More Like Turrets With A Health Bar, And Make Their Projectiles Unaffected By Gravity. That Way, They're More Like A Mini-boss, Think Ultrakill's Defence System On The Earthmover, But More Plentiful. Maybe With That Method, You'd Need To Lower The Amount Of Crystals So It Doesn't Just Devolve Into Touhou. With The Forcefield Idea Though, I'd Put It Around The Centre Island Kinda Like A Smaller World Border. Heck, It Could Literally Be The World Border, And It Could Expand Fully Once The Dragon Is Defeated. That Way, Pegasi Could Keep Their Flight While Not Being Able To Escape Or Have It Easy.

For Caves, I Guess? I Mean, When I Think About It, I Can't Think Of Any Logical Way To Make My Method Work Without Some Complex Nonsense. Though I'm Also Not A Fan Of Your Idea, Since I'd Prefer Not Throwing Somepony Into A Wall At Mach 9 Because They Clicked The V Key, Though I Suppose It Wouldn't Be That Hard Of A Wind Current Likely. I Guess Occam's Razor Again, Just Add Ravenous Bats Or Something, That'd Actually Work Nicely If Bigger Than The Current Vanilla Bats For Hitbox Reasons.
(quick edit: you gotta remember sollace has to code this stuff if it gets added, and i think having the wind dynamically change based on world generation and the placing and breaking of blocks would give them a headache.)

For The Wind Generator Block, I Feel It Should Be More Of A Fan In That Case. Otherwise, I Love The Idea, Really Kicking Myself I Didn't Think Of A Fan That Generates Wind. I Stick By The Magic Deadzone Thing Though, Gotta Have Some Way To Protect Your Base From A Black Hole Spontaneously Appearing Or A Unicorn With An Axe That Does More Damage Than I Have Health Teleporting Inside Out Of Nowhere.

And Going Back To The End Fight For A Moment, I Suppose In An Ideal Situation:
The Earth Pony, With Their Damage Boost, Would Take On The Dragon When It Perches.
The Unicorn, With Their Spells, Would Act As Support, Pelting The Dragon With Their Magical Attacks And Healing Their Allies When Possible.
The Pegasus, With Their Flight, Taking Out The Crystals To Stop The Dragon From Regenerating HP And To Harass It Whilst It's Flying.
In That Situation, Everypony Has A Role In Defeating The Dragon, Which Is Good. (and no, i'm not accounting for the other species, i don't play the others and can't speak for how they work)

**Comment by PrinceDrowsy** [comment]
> Honestly That's A Fair Way Of Thinking. For The Nether, Even With Harder Flight, If You Can Fly At All You Can Skip Most Of The Challenge Of Getting To A Fortress, And I Find It Often Leaves Non-Pegasi Behind In The Dust From Multiplayer Sessions With My Friends, And That Is Something I'd Like To Avoid.
> 
> With The End, Thinking About It, I Suppose Another Way Of Looking At It Would Be To Make The Crystals More Like Turrets With A Health Bar, And Make Their Projectiles Unaffected By Gravity. That Way, They're More Like A Mini-boss, Think Ultrakill's Defence System On The Earthmover, But More Plentiful. Maybe With That Method, You'd Need To Lower The Amount Of Crystals So It Doesn't Just Devolve Into Touhou. With The Forcefield Idea Though, I'd Put It Around The Centre Island Kinda Like A Smaller World Border. Heck, It Could Literally Be The World Border, And It Could Expand Fully Once The Dragon Is Defeated. That Way, Pegasi Could Keep Their Flight While Not Being Able To Escape Or Have It Easy.
> 
> For Caves, I Guess? I Mean, When I Think About It, I Can't Think Of Any Logical Way To Make My Method Work Without Some Complex Nonsense. Though I'm Also Not A Fan Of Your Idea, Since I'd Prefer Not Throwing Somepony Into A Wall At Mach 9 Because They Clicked The V Key, Though I Suppose It Wouldn't Be That Hard Of A Wind Current Likely. I Guess Occam's Razor Again, Just Add Ravenous Bats Or Something, That'd Actually Work Nicely If Bigger Than The Current Vanilla Bats For Hitbox Reasons. (quick edit: you gotta remember sollace has to code this stuff if it gets added, and i think having the wind dynamically change based on world generation and the placing and breaking of blocks would give them a headache.)
> 
> For The Wind Generator Block, I Feel It Should Be More Of A Fan In That Case. Otherwise, I Love The Idea, Really Kicking Myself I Didn't Think Of A Fan That Generates Wind. I Stick By The Magic Deadzone Thing Though, Gotta Have Some Way To Protect Your Base From A Black Hole Spontaneously Appearing Or A Unicorn With An Axe That Does More Damage Than I Have Health Teleporting Inside Out Of Nowhere.
> 
> And Going Back To The End Fight For A Moment, I Suppose In An Ideal Situation: The Earth Pony, With Their Damage Boost, Would Take On The Dragon When It Perches. The Unicorn, With Their Spells, Would Act As Support, Pelting The Dragon With Their Magical Attacks And Healing Their Allies When Possible. The Pegasus, With Their Flight, Taking Out The Crystals To Stop The Dragon From Regenerating HP And To Harass It Whilst It's Flying. In That Situation, Everypony Has A Role In Defeating The Dragon, Which Is Good. (and no, i'm not accounting for the other species, i don't play the others and can't speak for how they work)

True, but it would be high risk high reward. A strong wind current in the Nether where there are pits of lava to fall into and low ceilings/other formations to crash into would make the flight incredibly risky. It'd basically nerf it down to match teleportation in the Nether. That, and fortresses are already hard to find anyways. Or maybe that's just me and my terrible navigational skills, haha.

The turret concept could be implemented via skulker potentially, or some variant of them. I was already thinking anyways that, for pegasi, skulker hits could disrupt their flight by "causing them to lose balance" so to speak.

Oooo, you could utilize the vampire bats from the show for the caves!!! Perhaps a more aggressive cave variant of an otherwise neutral mob, kinda like what cave spiders are to regular spiders? That, and you could make the flyders from the show and have them be the size of cave spiders, or slightly smaller. 
(And in my defense, Sollace did manage to implement my ocean wind system suggestion, which is pretty dang impressive to say the least.)

I'm glad you liked my wind generator/fan block suggestion!!! And for magic, I was thinking the Crystal Heart could be used to prevent the use of dark magic in a given area. Not all magic, but it could eliminate the use of things like the black hole that would cause insta-murder and too-quick-to-prevent griefing and whatnot. For teleportation, you just need to prevent them from having direct line-of-sight to whatever area you want to defend. Build a high enough wall with a strong outcropping/walled lip at the top, and they can't really get in with teleportation. Helps that ponies are already somewhat smaller than the average player from what I can tell.

And on your last note, I fully agree!! After all, the show's all about friendship and teamwork. I firmly believe this mod should be most fun when played in multiplayer.

**Comment by Sollace** [comment]
Two changes implemented:

1. Fixed `Have No Infinite Flight With Clicking V Occasionally. `
2. Flying over the void now costs twice as much and exhausts you a lot more quickly.

It's kind of the middle of the night, but I was thinking of also adding a status effect: Broken Wings.

Let me know what you think of this idea.

Flying mobs not a new idea. If it happens, it wouldn't be very soon.

> Add Spells To Counter Flight

Unicorns already have several spells they can use against pegasi if they're creative with how they cast them.

> 4. Give Skeletons Better Aim And Priority On Flying Pegasi.

This is a maybe™️

> 5. Have No Flight In Enclosed Spaces

Not planned. If a pegasus wants to bonk their head, I have no interest in stopping them. [There's even an enchantment that lets them do it safely](https://github.com/Sollace/Unicopia/wiki/Enchantments#padded)

> 7. Add A Block That Creates A Flight Deadzone.

Area protection spells should be able to do this, as they are current intended to negate magic and pegasi use magic to fly (that is the canonical reason for why it consumes mana). I'd have to implement support for it though.

> Heat rises, so having additionally strong wind currents in the Nether should give some mild nerfing while still providing the fun of attempting to fly through the current nonetheless,

Lava already provides a significant updraft, so /shrug

>  That, and you could make the flyders from the show and have them be the size of cave spiders, or slightly smaller.

Intrusive thought: Have them the size of regular minecraft spiders.

**Comment by PrinceDrowsy** [comment]
> It's kind of the middle of the night, but I was thinking of also adding a status effect: Broken Wings.
> 
> Let me know what you think of this idea.

LOVE this idea!!!! I'm always a huge fan of unique status effects, and I'd love to see how you execute this. Ignore this if it's incredibly difficult to implement or just plain impossible, but I would love to see players be able to induce this by hitting the wings of a pegasus specifically with either an axe or an arrow (if in flight). If it doesn't exist already, perhaps unicorns could also have a Magical Exhaustion effect if they continually overextend their mana while casting? We see Twilight Sparkle experience this in canon in the earlier seasons, particularly when she was teleporting frequently, especially when she wasn't nearly as skilled at the spell as she becomes in later seasons.
 
> > 4. Give Skeletons Better Aim And Priority On Flying Pegasi.
> 
> This is a maybe™️

![My-Little-Pony-PNG-HD-1520464978](https://github.com/Sollace/Unicopia/assets/75338505/e4219fdf-0ad4-4eca-976a-8519e714aae0)

> > 7. Add A Block That Creates A Flight Deadzone.
> 
> Area protection spells should be able to do this, as they are current intended to negate magic and pegasi use magic to fly (that is the canonical reason for why it consumes mana). I'd have to implement support for it though.

The fan blocks at the very least could still have some similar utilization purposes for earth ponies and other pegasi, along with being good for fun things like obstacle courses, adventure maps, perhaps a tool in assisting fliers to reach higher heights more easily, helping with tricks, etc. They'd be superior to using lava and the like to produce currents since you could control the power with which the wind produced flows, along with aiming them in other directions than straight up.

However, I understand not implementing them if the process would be too difficult or just plain impossible.

> > Heat rises, so having additionally strong wind currents in the Nether should give some mild nerfing while still providing the fun of attempting to fly through the current nonetheless,
> 
> Lava already provides a significant updraft, so /shrug

I meant something more like how the wind flings you during storms, but I see your point nonetheless.

> > That, and you could make the flyders from the show and have them be the size of cave spiders, or slightly smaller.
> 
> Intrusive thought: Have them the size of regular minecraft spiders.

Ohohoho.... That would be so funny. I love that so much. If you ever implement them, please do. I would love to scare the shit out of friends with that.

**Comment by EternaDash** [comment]
> It's kind of the middle of the night, but I was thinking of also adding a status effect: Broken Wings.

It'd Probably Work Better In A FirstAid Compat Update Like Suggested In My Issue #385 

> > That, and you could make the flyders from the show and have them be the size of cave spiders, or slightly smaller.
> 
> Intrusive thought: Have them the size of regular minecraft spiders.

That Sounds Utterly Terrifying, I Love It
