### ISSUE TITLE
Infinite Wheat Worms If You Give A Crap For Some Reason

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#373]
Step One: Break Dirt
Step Two: Place Dirt
Rinse And Repeat Forever

Yeah It's That Simple, For Some Reason You Can Get Wheat Worms From Non-Naturally Generating Dirt, Or In Lame Speak: Dirt You Place. Which Does Mean You Can Repeatedly Mine And Place The Same Dirt Block, And Rack Up Infinite Wheat Worms.
Now, Yes, It's Wheat Worms, Just Barely More Useful Than Poisonous Potatoes, But I'm Pretty Sure The Only Thing That Would Need To Be Done To Fix This Issue Is To Shrimply Add A Check To Not Allow For Wheat Worm Collection From Player-Placed Dirt.
Besides, If Someone Has A Wheat Worm Economy For.. Some Reason... This Will 100% Cause Round Two Of [Venezuelan Hyperinflation.](https://en.wikipedia.org/wiki/Hyperinflation_in_Venezuela)

Edit: I Just Realized Wheat Worms Are Perfectly Edible By Changelings, And Give Decent Saturation In Big Numbers. So Actually, This Is An Infinite Food Glitch For Them. So That Wheat Worm Economy Joke Is Actually A Lot More Realistic (in-game at least) When You Think About It.. Huh...

**Comment by Sollace** [comment]
Not really possible to distenguish between regular and player-placed dirt, and besides I don't make the worms replace the dirt otherwise that's lost resources.

Also you use wheat worms to convert gravel to course dirt (I believe). I know there's potential to farm the worms, in the same way you can farm flint from gravel, so.
