### ISSUE TITLE
Drop one feather trigger too many advancement

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#378]
<img width="1916" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/00e25ece-6f85-4c67-8ef0-bb4fec387275">

**Comment by Sollace** [comment]
It's based on a trigger that uses a counter to keep track of how many times it's been fired. The counter is saved separately so the first time it fires after the advancements were added it will give you all the ones you would have had since you started the world.

There's no way to really fix this, nor would consider it a bug. It's doing what it's supposed to here.
