### ISSUE TITLE
Hi, Here's A Metric Buckton Of Ideas.

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#397]
Hi.
I Think Of A Lot Of Things.
Some Good, Some Bad, Some Separating Descending And Diving.
Here's All Of My Ideas,
Because Honestly Might As Well,
And Maybe Some Are Good.
*(quick confession: i haven't watched the show. like at all. how i even got into mlp is a story in itself, but that's not for today)*

⠀

General: Either Ideas I Don't Have Much To Say On Or Seeds Still Being Too Good
=====================================================

Make Seeds Not As Good As Wheat: Speaking Of Seeds-! So Long As They Match Eachother In Hunger And Saturation, It's Just More Worth Your Time To Break Grass For Seeds Rather Than Growing Wheat Out Of Them. If Anything, Since You Get Back More Seeds Than Wheat, It's Still More Worth It To Ditch The Wheat Itself.

Everfree Forest Biome: Simple As That, Really. New Biome With Unique Wood Type, Home To New Mobs As Listed Later In This Issue.

Instruments: Listen, My Favourite Pony Is Octavia Melody, I Was Inevitibly Gonna Suggest Instruments Someday And That Day Is Now. Hey, It'd Make Roleplay More Fun And Immersive At Least.

Mobs Can Use Racial Abilities: Pegasus Zomponies Can Fly, Unicorn Zomponies And Skeletons Can Use Spells, Earth Zomponies Do More Damage, You Get The Idea For Every Other Mob That In MineLP Are Ponified.

⠀

Earth Pony: Suggestions That Revolve Around The Earth Pony In Some Capacity
====================================================

Potion Of Fortification: Pairs Nicely With #396 Where I Suggested Fortification To Work When Uncrouched If The Player Managed To Get It With Commands. But Who Says It Should Be *Only* For Commands And Crouching Earth Ponies? For A Potion Of Fortification, I Say Brewing With Netherite Scrap Would Be Fitting, With How Netherite Armour Gives You Knockback Res. If You Go This Route, You Can Even Divide Fortification Into Two Levels, Level One Being 50% Knockback Reduction And Level Two Being 100% Knockback Reduction.

More Crops On Harvest: Simple Suggestion To Make Earth Ponies More Valuable. When Harvesting A Crop Like Wheat Or Oats, The Earth Pony Would Produce Double The Standard Yield.

Eat Gemstones: In The Spellbook, It Says Farm-Ponies Considered Them A Delicacy, Implying They'd Eat Them. So, Why Can't We In Game? Also, I Just Find It Unendingly Funny Thinking Of An Earth Pony Walking Into A Unicorn's House And Just Vacuuming All Their Gemstones.

Slam Ability Not Being Instant: Let's Be Real, Being Able To Literally Teleport To The Ground In An Instant Is Kinda Goofy. Just Making The Pony Fall Really Fast But Not Instantly Would Work.

Slam Ability Not Negating Fall Damage Entirely: In My Opinion, The Slam Ability Should Instead Push Back The Distance Before Taking Fall Damage To 10 Blocks Up, Then Continue As Normal.

Give Crushing Blow Some Actual Range: For Me, I Need To Basically Be Inside A Creature To Hit With Crushing Blow. And At That Point, Just Crit-Axe Them.

Make Cider Drinkable By Earth Ponies: My Idea Is Giving The Earth Pony Strength I For 30 Seconds, But Mining Fatigue I And Slowness I For 2 Minutes, On Top Of Weakness I For 1.5 Minutes After The Strength Wears Off.

⠀

Pegasus: Suggestions That Revolve Around The Pegasus In Some Capacity
=================================================

Nerf To Bows Mid-Flight: Being Able To Slow Down Mid-Air With A Bow To Hit Shots Is Nice, But Kinda Strong. So Maybe Remove That, And Instead Give That To My Next Idea.

Pegasus Bow: Combos Nicely With #367 And The Idea Of Pegasus Arrows, Made Like A Bow But With Two Pegasus Feathers, And Fires Arrows At Faster Speeds. Incompatible With Infinity, Mending, And Flame Enchantments. Repaired With Pegasus Feathers. Can Be Fired Mid-Flight While Stopping Mid-Air. Skeletons Can Rarely Spawn With One Instead Of A Regular Bow.

Make Clouds Completely Transparent To Light: Big Blotches Of Cloud Basically Act As Natural Mob Spawners All-Day As Of Right Now. That Isn't Particularly Ideal.

Heavy Armour Nerfs Flight: Armour Like Iron, Diamond, And Netherite, Are All Probably Real Heavy, And Therefore Would Make Flight Slower And More Taxing. This Could Also Be Automatically Compatible With Other Mods If Weight Is Determined By Armour Value.

Heavy Is A Curse: Speaking Of Weight, Literally Who Wants To Go Slower? It's A Curse, Something You Don't Want. Inverse Situation As With Clingy, Which *Was* A Curse But Is Something You'd Want On Your Item.

Drop Pegasus Feathers On Death: Tad Silly Of An Idea In The Context Of The Mod, But I Like The Saying That If Friendship Is Magic, Then Magic Means Destruction. Could Be A Gamerule Where Pegasi Drop 0-2 Feathers On Death, And A Separate Gamerule Where They Either Drop When Dying In Any Way, Or When Killed By Another Pony. Probably Should Be Off By Default, So Default Incentive Isn't To Make The Rainbow Factory As Soon As Possible.

⠀

Unicorn: Suggestions That Revolve Around The Unicorn In Some Capacity
=================================================

Teleport Far Doing It's Job: At Least For Me And My Comrades, It Basically Does Nothing Compared To Normal Teleport.

Xray Spell: Function Is Simple: Applies Glowing To All Mobs In Range. Works Well Against Tatzlwurms That Are Suggested Later On.
*i, uh, can't think of much for unicorns.*

⠀

Zebra: Suggestions That Revolve Around The Zebra In Some Capacity
==============================================

Their Existence In The First Place: I Know Some Of Us Wanna Play As Zecora, So I'm Adding This In My List.

Potion Brewing Expertise: From What I Know About Zecora, They Make Potions. So Brewing Stands Nearby Zebras Will Brew Faster And Potions Outputted Will Last Longer Than Usual.

Full Neutrality To Everfree Mobs: Any Mob That Normally Attacks The Player Under Certain Circumstances Or Just At All Are Completely Neutral To Zebras And Will Only Attack If Attacked Themselves.

Everfree Wood Doors Only For Zebras: Everfree Wood Doors Would Only Be Openable By Zebras, Kinda Like The Crystal Door Or Cloud Door.

Everfree Wood Takes Twice As Long To Mine For Non-Zebras: Speaking Of Everfree Wood, Anything Related To It Takes Twice As Long For Non-Zebras To Mine- Or I Guess Chop.

Natural Resistance To Poison: Poison Damages Half As Much When Afflicted To A Zebra. Or Just Doesn't Damage Them At All If You Can't Slow Poison When Coding It. This Does Not Give Immunity To The Wither Effect.

Brewing Cauldron: Crafted With Everfree Planks Like A Cauldron, The Interface Can Only Be Opened By A Zebra. Brewing Cauldrons Can Combine Two Potions To Also Combine The Effects. This Costs XP Depending On The Effects Combinded, And Opposites Cannot Be Combinded Like Regen And Poison/Wither.

⠀

Changeling: Suggestions That Revolve Around The Changeling In Some Capacity
=====================================================

Hivemind Chat: Chat Exclusive To Changelings, Pretty Simple.

Strength In Numbers: The More Changelings Nearby, The More Damage They Each Do And The More Love They Consume, Capping At 4 Changelings. Would Be Tied To Gamerule.

Weakness In Solitary: When Alone, A Changeling Would Do Less Damage. This Would Not Apply If There Is Only One Changeling, For Fairness And Viability In Singleplayer. Would Also Be Tied To Gamerule.

Weakness To Fire: I Know Insects And Bug-Type Pokémon Really Don't Mix Well With Fire, So Double Damage To Fire And Lava Seems Like It'd Make Sense To Me.

Major Changeling Tribe: Similar To Alicorn But For Changelings, Also Only Being Accessible With Cheats. Basically Making Chrysalis Playable.

⠀

Mobs: Mob Ideas. Might Be Tad Limited Since, Well, Check My Confession Earlier.
=====================================================

Phoenix:
Health: 10-ish?
Damage: Doesn't Attack
Nature: Passive
Drops: 0-1 Phoenix Feather
Special: Can Fly
Spawns In: Overworld (rare)
Note: Looks Cool And Phoenix Feather Could Be Useful

Timberwolf:
Health: 20
Damage: 5 (easy) 8 (normal) 12 (hard)
Nature: Hostile
Drops: 1-2 Everfree Logs, 2-4 Sticks
Special: Takes Triple Damage To Fire
Spawns In: Everfree Forest (light 0, above sea level, in packs 2-4 in size)
Note: Makes Everfree Logs Easier To Farm Compared To Other Wood, So That's Neat

Ursa Minor:
Health: 40
Damage: 9 (easy) 13 (normal) 16 (hard)
Nature: Neutral (attacks if approached or attacked)
Drops: 1-3 Stardust
Special: Despawns In Light Above 7
Spawns In: Everfree Forest (light 0, night, above sea level, uncommon)
Note: Honestly I Just Like The Idea Of A Mob That Outright Vanishes At Day

Windigo:
Health: 1
Damage: Doesn't Attack (directly)
Nature: Hostile
Drops: Nothing
Special: Nearby Mobs Freeze Like In Powdered Snow, Can Only Be Damaged With Fire
Spawns In: Snowing Biomes (above sea level, nearby when at least 5 mobs die in 10 seconds counting pony deaths)
Note: Probably The Weakest Of My Mob Suggestions Tbh

Cragadile:
Health: 20
Damage: 15 (easy) 18 (normal) 22 (hard)
Nature: Neutral (attacks if in water or attacked)
Drops: 2-4 Cobblestone
Special: Doesn't Exit The Water Unless Attacked, Swims At Double A Regular Pony's Speed When Aggro'd
Spawns In: Everfree Forest (only in water, rare)
Note: Cobblestone Is More Easily Farmable, Yippee

Tatzlwurm:
Health: 10
Damage: 5 (easy) 7 (normal) 9 (hard)
Nature: Neutral (attacks when detecting vibrations on the ground, like breaking blocks or walking, does not detect crouching, attacks any mob)
Drops: Nothing
Special: Worm Creature That "Swims" Through Terrain (like terraria worm monsters), Takes Half Damage To Non-Magical Attacks, Attack Animation That Lasts Half A Second (to allow a pony to dodge if aware), Does Not Go Above y=50 Willingly
Spawns In: Below y=30 (inside terrain, rare)
Note: Really Unsure What They Could Drop

Changeling (mob):
Health: 20
Damage: 6 (easy) 8 (normal) 10 (hard)
Nature: Hostile
Drops: 0-2 Carapaces
Special: Larger Attack Reach Than Usual, Heals 3 Hearts Per Attack Regardless Of Difficulty, One Seeing A Target Means All Can See The Target And Will Collectively Aggro, Attacks Villagers, Neutral Towards Changeling Players
Spawns In: Overworld (light 0, packs of 2-4, less common underground, uncommon)
Note: Surprised They Aren't Already In The Mod As A Mob

⠀

Extras: Stuff That Doesn't Fit Anywhere Else
=============================

Human As A Selectible Tribe: Maybe You Wanna Be A Human Without Cheats For Some Reason. Don't Know Why, But Why Isn't My Problem.

Potion Of Resistance: Yeah You Can't Normally Make One. Brewed With An Iron Block (it's common enough you'll be fine).

Phoenix Arrows: Fire Arrows All Without The Need For The Flame Enchant. Incompatible With Infinity Enchantment. Can Be Found In Chests Rarely As Loot. Crafted Like A Normal Arrow But With A Phoenix Feather. Skeletons Can Rarely Fire These Instead Of Regular Arrows On Hard.

Phoenix Banner Pattern: Banner Pattern Made With A Phoenix Feather That, Unsurprisingly, Looks Like A Phoenix.

Potion Of Rebirth: Made With Brewing A Phoenix Feather With A Potion Of Resistance II. Lasts 7 Seconds, But Dying With The Effect Will Remove It And Act As A Totem Of Undying.

Recipe For Totem Of Undying: 5 Gold Ingots, 1 Phoenix Feather, 1 Diamond, 2 Stardust. Totems Are Already Dirt Cheap With Raid Farms, So This Doesn't Seem Like A Horrible Idea. Maybe Add In A Netherite Ingot If You Want.

Stardust In Potion Brewing: Makes Potions More Extreme Than They Already Are. So A Strength Potion Brewed With Glowstone To Be Strength II, Then Is Brewed With Stardust, Becomes Strength III. Or A Night Vision Potion Brewed With Redstone To Last 8 Minutes, Then Brewed With Stardust, Lasts 12 Minutes. And Yes, That Does Mean You Can Get Resistance V With Turtle Master, But It'll Last Even Less Time.

Stardust Torch: Torch Plus Stardust Makes A Stardust Torch. Same As Torch, But Ursa Minors Don't Despawn To It's Light. Useful If Making A Farm And You Only Want Ursa Minors To Spawn. Plus Decorative.

Starlight Block: Created Like Glowstone But With Stardust, Emits Light Level 15, Mainly Decorative.

Potion Of Starlight: Brewed With A Starlight Block, Makes The Affected Entity Glow Like A Light Source. Finally, Glowing Glow Squids.

Starsteel Ingot: Crafted With 8 Stardust Surrounding An Iron Ingot. Gear Made With It Is As Strong As Diamond And The Armour Emits Light. Starsteel Sword Sets Targets On Fire, And Is Incompatible With Fire Aspect. Full Set Of Armour Grants Fire Resistance.

⠀

End
===

If You've Actually Read All Of That: Hi Again.
Likely Not All Are The Greatest Ideas, But It's Better To At Least See What Others Think, Right?
I'm Also Pretty Confident This Is The Longest Issue Posted On This Github, So- Uh... Sorry About That I Guess.

**Comment by Sollace** [comment]
1. Far teleport is for teleporting through walls. Versus the normal variant that takes you to the side closest to you.
2. "Xray Spell" No exploitables
3. "Everfree Forest Biome" Already requested
4. "Instruments" Not planned
5. "Mobs Can Use Racial Abilities" Not planned
6. "Potion Of Fortification" No
7. "More Crops On Harvest" Earth ponies can already grow crops on demand. No.
8. "Eat Gemstones" This was a reference to the pie family. Also you can make rock soup so this is already a thing.
9. . "Heavy Is A Curse" Heavy reduces knockback and makes you stronger against unicorn shields similar to fortification. No.
10. "Slam Ability Not Being Instant" Slam is not instant. It applies a downwards velocity.
11. "Slam Ability Not Negating Fall Damage Entirely" No.
12. "Give Crushing Blow Some Actual Range" No.
13. "Make Cider Drinkable By Earth Ponies" They can already drink it. I don't see any reason to give them status effect. No.
14. "Drop Pegasus Feathers On Death" Pegasi already drop feathers during flight
15. "Nerf To Bows Mid-Flight" No.
16. "Zebra" Already requested
17. "Changeling" Make this a separate issue
18. "Mobs" Half already requested, half not planned. I'll get to it when I get to it.
19. "Human As A Selectible Tribe". Use commands
20. "Potion Of Resistance" No
21. "Phoenix Arrows" Put this with mobs
22. "Phoenix Banner Pattern" Put this with mobs
23. "Potion Of Rebirth" We already have potions to respawn with other races I'm not adding redundant items
24. "Recipe For Totem Of Undying" Absolutely not
25. "Stardust In Potion Brewing" No
26. "Stardust Torch" Put this with mobs
27. "Starlight Block" Put this with mobs
28. "Starsteel Ingot" No ores

I am sick and tired of these massive wishlist issues.

Most of the time these are filled with things that have already been requested in other issues, are asking for things I already planned to do (but can't because people keep making these massive wishlists) or it's some massive new expansion that would take me months to do or it's some balancing discussion that goes against other feedback I've gotten that _honestly needs to be its own issue_.

These long issues are too much. I can't deal with them. Simply sitting down to have to _read them_ is a massive drain on my time and at the end I have to make a decision whether to add all of it, or none of it. I can't separate the good ideas from the bad ideas if they're all smashed together like this.

I also use github issues to keep track of what what's done and what needs doing. If I can't do that by looking at the title, chances are low I'm even going to look at it.

If you want even a remote chance at any of this being added to the game: make separate issues.

Make them short.

Make it something I can work with that's not a giant essay of random half-related concepts and ideas. You can repost most of these as their own issues or under existing issues and I'll consider them separately. For now though I have to close this because I can't add _everything_ here.

**From now on if I see other issues that just list things I will close it withouth comment**

Some other random notes:
I can't nerf seeds again. Nerfing seeds nerfs _all nuts_.

I'm not making bows worse for pegasi. Pegasi have already been nerfed so flying is harder over the void and skeletons already target them over other mobs _and hit them with more accuracy._ I honestly feel like I've been unfair to pegasus players because most of the changes in this update _are nerfs_. I don't want to nerf them more. They need bows. This is not changing.

I am not adding recipes for OP vanilla items. That is not what this mod is for.

Fortification is an earth pony specific ability. Only they can use it. You're not supposed to have it if you're not an earth pony. The status effect is only an icon there to tell you when it is active.

**Comment by Sollace** [comment]
Duplicate of #138
Duplicate of #116
Duplicate of #144

**Comment by Sollace** [comment]
Duplicate of #229

**Comment by MimzyFang** [comment]
@EternaDash please make individual issues for each feature and check if things have been already requested and don't request those again

**Comment by EternaDash** [comment]
i only made these so big because i didnt want to clog up the issues list with a bunch of individual additions all from me.

just ow.

**Comment by EternaDash** [comment]
it feels wrong just leaving off with a short message so heres a longer one.

@Sollace i made these big lists because i didnt want to be an annoyance, i wanted to not clog up the issues with a bunch of random things. so i bundled them into one neat list. i didnt know that was worse, and i dont know why i wasnt told that earlier on.
and i know its a lot of stuff and you yourself said i could repost these as individual issues and they'd be genuinely considered, but that big list of dismissive "no"s says otherwise.
i feel hurt. i poured my heart and soul into this because i wanted to help, i wanted to contribute. and now i dont even know if im welcome.

im sorry for annoying you. i just wish you worded what you said better.

**Comment by Sollace** [comment]
> it feels wrong just leaving off with a short message so heres a longer one.
> 
> @Sollace i made these big lists because i didnt want to be an annoyance, i wanted to not clog up the issues with a bunch of random things. so i bundled them into one neat list. i didnt know that was worse, and i dont know why i wasnt told that earlier on. and i know its a lot of stuff and you yourself said i could repost these as individual issues and they'd be genuinely considered, but that big list of dismissive "no"s says otherwise. i feel hurt. i poured my heart and soul into this because i wanted to help, i wanted to contribute. and now i dont even know if im welcome.
> 
> im sorry for annoying you. i just wish you worded what you said better.

Sorry, I could have been less harsh with what I said. And you're right I should have said something earlier. I was fine with letting the lists be because I didn't want to put you off from suggesting ideas, it's only when it started trending longer and coincided with a bad time on my part that I had to draw the line.

You are perfectly welcome to repost each _section_ from this issue as their own with them grouped more to their theme. It's just massive overhaul issues and readability that I take issue with.
