### ISSUE TITLE
Wild Raw Mushrooms Are Safe To Eat, Somehow.

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#406]
![image_2024-07-13_083804468](https://github.com/user-attachments/assets/5f565c9b-3521-4d72-8170-7f5e1f66b558)
By All Accounts If I Eat A Wild Mushroom Raw, Chances Are I Am Becoming A Statistic. Red Mushroom Is Also Edible Which, Seeing It's Appearance, Is Even More Likely To End My Continued Existence.
![image](https://github.com/user-attachments/assets/40afdf74-2f8b-4cfe-8624-b00eeaf956fd)
I Don't Believe Being A Herbivore Makes You Immune To Deadly Toxins.

**Comment by PrinceDrowsy** [comment]
The mushrooms aren't toxic in-game, makes no sense for this kind of mod to suddenly force players to deal with IRL shroom toxicity when there are only two kinds in Minecraft and both are used in the stew crafting recipe. Can't even argue that cooking makes it less toxic as the red mushroom is based on a shroom that'd be toxic no matter what you did with it. Would be better off as a more generalized suggestion for improved foraging as a counterpart of the mod's dietary restrictions system.

**Comment by PrinceDrowsy** [comment]
Adding new kinds of plant-life for non-earth ponies to forage for could actually be a really fun concept now that I think about it...

**Comment by EternaDash** [comment]
Eh, Either Way, It Gives More Saturation Than Wheat So Best Strat Is To Just Become Mario For Food

**Comment by Sollace** [comment]
Mushrooms are in the same class as most plant matter. It's edible because... in-game you can eat them (mushroom stew) and irl there are edible variants of mushrooms that are safe.

Since the game has them as safe, I made them safe, also to expand the roster of things earth ponies can eat. If I expand the selection of things you can eat, I'll probably give them the same treatment as the orchids and ferns where the different variations have different effects when you eat them.

**Comment by MimzyFang** [comment]
@EternaDash please report this behavior here lol
https://bugs.mojang.com/
