### ISSUE TITLE
Ability Page Up And Page Down Keys

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#415]
1. Who Uses PageUp And PageDn Keys Anyways?
2. Nowhere Does It Say That You Have A Second Page Of Abilities Outside Of In Controls

Here Are My Suggestions

1. Make The Default Keys Up Arrow And Down Arrow, Makes More Intuitive Sense
2. Add A Little ui Element Next To Your Abilities That Tell You This In The First Place

**Comment by PrinceDrowsy** [comment]
I pitched a skill wheel as a rework for how the abilities menu works, but that might've been too complex a suggestion, haha. I still however believe that something similar should really be done. 
![232115247-ec5b94ae-efc2-4001-bd2a-6f451a6a5a4a](https://github.com/user-attachments/assets/2ab1366f-abd6-46da-98c9-6bc011155460)
This was the menu replacement in my original suggestion, which is a radial menu, *however* perhaps an easier version could be a square like this instead? 
![image](https://github.com/user-attachments/assets/775fc224-2066-45b7-81c9-4e1170ed887a)
Opened by holding the primary ability key, you can swiftly click on one with your mouse much like you select a tribe with the tribe selection menu, but with only one click to select the skill instead of clicking to open the tribe description and then clicking a second to accept. After selecting the skill, you can tap instead of hold the primary ability key to use it.
![image](https://github.com/user-attachments/assets/85fb1c06-1542-4843-9141-82d25d8d23ad)
Increasing the abilities on the page could look something like this? And an additional page can be added to scroll through with the arrow keys if necessary, but it would still be useful in that you could select more skills on one page than you can with the current system, along with reducing the amount of keys bound to abilities alone. It'd also just be way easier to get a closer look at your abilities and admire the icons.

That, and it'd be nice to have more slots to store spells in, haha. The less gemstones in my hotbar the better.

**Comment by PrinceDrowsy** [comment]
On an alternative note for spells in particular though, it could be really nice to have an additional hotbar for favorited spells. Your UI would look completely normal until activating the spell hotbar using the secondary ability key. It would be then that a second hotbar appears above your regular hotbar, looking something like this:
![image](https://github.com/user-attachments/assets/6fe3ac26-447c-45d2-b713-5e5060a819fc)
You would be able to place gemstones/spells in here using the spellbook (spells only, unicorns don't get to use this hotbar for more item storage) and when activated, use the numbers you would normally use to flip between boxes in your regular hotbar to instead select which spell to use. It would then automatically close after your selection is made, and you can then cast the selected spell with the primary ability key.

This could potentially work in tandem with the skill wheel (square?) concept above to switch between using the primary key to cast spells vs. utilize other abilities.
