### ISSUE TITLE
Bat-Pony sunlight debuff

### ISSUE THREAD

**Issue by Storylover-Vodhr** [Sollace/Unicopia#58]
I feel the batpony debuff for being in sunlight is a bit extreme. The blinding effect is perfectly fine; it's mostly just the high pitched screeching effect. 

Is it possible to have the sound effect to be lessened, or maybe have it slowly increase to the current level depending on how long the player is in the sun? It's mostly just the volume level that's a problem, rather than the effect itself.

And a secondary question is this; is it possible for a ability to limit the debuff in general on a server, to prevent random flashbanging of Bat-pony players when enough people sleep to skip the night whilst the batpony is flying about?

**Comment by Sollace** [comment]
> is it possible for a ability to limit the debuff in general

Wearing any of these items will protect bat ponies's eyes from the sun:
https://github.com/Sollace/Unicopia/blob/1.19/src/main/resources/data/unicopia/tags/items/shades.json

It's an item tag, so servers should be able to add additional items to that list if they wish to customise it.

> have it slowly increase to the current level depending on how long the player is in the sun?

The current effect is meant to simulate a flashbang/exposure to bright light. I might implement this suggestion, though, or otherwise adjust the volume so it's less intense.

**Comment by ghost** [comment]
Most of the bat ponies in my server play as pegasus just to avoid it.  It's a cool concept but a bit too punishing, especially if you've just joined the server and your first experience is having to dig underground instantly to be able to see and hear.  Just my two cents on the matter, I think having the option to give up your night vision in exchange for no sun blindness would be good.  Maybe a "day bat" race, leave the option available for the hardcore bat role players while also giving a more forgiving option.
