### ISSUE TITLE
Unicopia crashes when using quilt

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#84]
Unicopia seems to have issues with quilt when opening the create new world screen
Unicopia git: 
https://mclo.gs/JXpXa4P

and Unicopia 1.0.0-beta.27: 
https://mclo.gs/aZgWaQB

Quilt loader version:
0.17.7

Quilted Fabric API (QFAPI) and Quilt Standard Libraries (QSL) versions:
QFAPI 4.0.0-beta.23 
QSL 3.0.0-beta.22

**Comment by Sollace** [comment]
Looks like the loader quilt is using has a different implementation from fabric-loader, because the net/fabricmc/loader/impl/util/Arguments class is missing there. I also see a lot of mixins failing there outside of this mod, and GSON is behaving differently which is causing configs to not load.

Not sure which of those you can report to Quilt, but my recommendation for now is to not use Quilt, for either Unicorn or anything that uses Kirin's json configs.
